package com.testgen.cicd;

import com.testgen.model.TestCase;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class ProjectGeneratorService {

    public byte[] generateZip(String framework, String projectName, List<TestCase> cases) throws Exception {
        String name = projectName.replaceAll("[^a-zA-Z0-9-]", "-").toLowerCase();

        var baos = new ByteArrayOutputStream();
        try (var zos = new ZipOutputStream(baos)) {
            addEntry(zos, "pom.xml",                                           pom(name, framework));
            addEntry(zos, "src/test/java/com/generated/GeneratedTests.java",   testClass(framework, cases));
            addEntry(zos, ".github/workflows/ci.yml",                          githubActions(framework));
            addEntry(zos, "README.md",                                         readme(name, framework));
        }
        return baos.toByteArray();
    }

    private void addEntry(ZipOutputStream zos, String path, String content) throws Exception {
        if (path.contains("..")) throw new SecurityException("Bad path: " + path);
        zos.putNextEntry(new ZipEntry(path));
        zos.write(content.getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }

    private String pom(String name, String framework) {
        String dep = switch (framework.toLowerCase()) {
            case "selenium" -> """
                    <dependency>
                        <groupId>org.seleniumhq.selenium</groupId>
                        <artifactId>selenium-java</artifactId>
                        <version>4.18.1</version>
                    </dependency>""";
            case "restassured" -> """
                    <dependency>
                        <groupId>io.rest-assured</groupId>
                        <artifactId>rest-assured</artifactId>
                        <version>5.4.0</version>
                        <scope>test</scope>
                    </dependency>""";
            default -> "";
        };

        return """
            <?xml version="1.0" encoding="UTF-8"?>
            <project xmlns="http://maven.apache.org/POM/4.0.0"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                         http://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.generated</groupId>
              <artifactId>%s</artifactId>
              <version>1.0.0</version>
              <properties>
                <maven.compiler.source>17</maven.compiler.source>
                <maven.compiler.target>17</maven.compiler.target>
              </properties>
              <dependencies>
                %s
                <dependency>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-jupiter</artifactId>
                    <version>5.10.1</version>
                    <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.1.2</version>
                  </plugin>
                </plugins>
              </build>
            </project>
            """.formatted(name, dep);
    }

    private String testClass(String framework, List<TestCase> cases) {
        var sb = new StringBuilder();
        for (var tc : cases) {
            String code = tc.getCodeSnippet() != null ? tc.getCodeSnippet() : "// TODO";
            sb.append("    // ").append(tc.getType()).append(": ").append(tc.getTitle()).append("\n");
            sb.append("    @Test\n");
            sb.append("    public void ").append(safe(tc.getMethodName())).append("() {\n");
            sb.append("        ").append(code.replace("\n", "\n        ")).append("\n");
            sb.append("    }\n\n");
        }

        return """
            package com.generated;

            import org.junit.jupiter.api.Test;
            import static org.junit.jupiter.api.Assertions.*;

            // Generated by TestGen AI
            // Framework: %s  |  Test cases: %d
            public class GeneratedTests {

            %s}
            """.formatted(framework, cases.size(), sb);
    }

    private String githubActions(String framework) {
        return """
            name: Run Generated Tests
            on:
              push:
                branches: [ main ]
              pull_request:
                branches: [ main ]
            jobs:
              test:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4
                  - uses: actions/setup-java@v4
                    with:
                      java-version: '17'
                      distribution: 'temurin'
                  - name: Run %s tests
                    run: mvn test
            """.formatted(framework);
    }

    private String readme(String name, String framework) {
        return """
            # %s

            Generated with **%s** by [TestGen AI](https://testgenai.com).

            ## Run

            ```bash
            mvn test
            ```
            """.formatted(name, framework);
    }

    private String safe(String name) {
        if (name == null || name.isBlank()) return "generatedTest";
        return name.replaceAll("[^a-zA-Z0-9_]", "_");
    }
}